import type { Project, TeamMember, Sprint } from "./types"

export const projectsData: Project[] = [
  {
    id: "project-1",
    name: "E-commerce Platform",
    description: "A full-featured e-commerce platform with product management, cart, and checkout functionality.",
    type: "Web Application",
    techStack: ["React", "Node.js", "MongoDB", "Express"],
    startDate: "2024-03-01",
    endDate: "2024-06-30",
    progress: 78,
    teamMembers: ["john.doe@example.com", "jane.smith@example.com", "alex.johnson@example.com"],
    milestones: ["Project Setup", "Backend Development", "Frontend Development", "Testing", "Deployment"],
    membersRequired: "3-5",
    status: "active",
    githublink:"github.com/username/repo",
  },
  {
    id: "project-2",
    name: "Task Management App",
    description: "A collaborative task management application for teams to organize and track their work.",
    type: "Mobile Application",
    techStack: ["React Native", "Firebase", "Redux"],
    startDate: "2024-02-15",
    endDate: "2024-05-15",
    progress: 100,
    teamMembers: ["john.doe@example.com", "sarah.williams@example.com"],
    milestones: ["Design", "Core Functionality", "User Authentication", "Testing", "App Store Submission"],
    membersRequired: "1-2",
    status: "completed",
    githublink:"github.com/username/repo",
  },
  {
    id: "project-3",
    name: "AI-powered Analytics Dashboard",
    description: "An analytics dashboard with AI-powered insights for business intelligence.",
    type: "Web Application",
    techStack: ["Vue.js", "Python", "TensorFlow", "Flask"],
    startDate: "2024-04-01",
    endDate: "2024-08-31",
    progress: 0,
    teamMembers: [],
    milestones: ["Data Collection", "ML Model Development", "Dashboard UI", "Integration", "Testing"],
    membersRequired: "3-5",
    status: "applied",
    githublink:"github.com/username/repo",
  },
]

export const teamMembersData: TeamMember[] = [
  {
    id: "member-1",
    name: "John Doe",
    role: "Full Stack Developer",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 4.8,
    skills: ["React", "Node.js", "MongoDB", "TypeScript", "AWS"],
    projects: 12,
    email: "john.doe@example.com",
  },
  {
    id: "member-2",
    name: "Jane Smith",
    role: "UI/UX Designer",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 4.9,
    skills: ["Figma", "Adobe XD", "Sketch", "HTML", "CSS"],
    projects: 15,
    email: "jane.smith@example.com",
  },
  {
    id: "member-3",
    name: "Alex Johnson",
    role: "Backend Developer",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 4.5,
    skills: ["Python", "Django", "PostgreSQL", "Docker", "Kubernetes"],
    projects: 8,
    email: "alex.johnson@example.com",
  },
  {
    id: "member-4",
    name: "Sarah Williams",
    role: "Mobile Developer",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 4.7,
    skills: ["React Native", "Swift", "Kotlin", "Firebase", "Redux"],
    projects: 10,
    email: "sarah.williams@example.com",
  },
  {
    id: "member-5",
    name: "Jadhav Patel",
    role: "DevOps Engineer",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 4.6,
    skills: ["AWS", "Docker", "Kubernetes", "Jenkins", "Terraform"],
    projects: 9,
    email: "jadhav.patel@example.com",
  },
  {
    id: "member-6",
    name: "Aditya Kumar",
    role: "Data Scientist",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 4.8,
    skills: ["Python", "TensorFlow", "PyTorch", "Pandas", "Scikit-learn"],
    projects: 7,
    email: "aditya.kumar@example.com",
  },
  {
    id: "member-7",
    name: "Sanjay Gupta",
    role: "Frontend Developer",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 4.4,
    skills: ["React", "Vue.js", "JavaScript", "CSS", "Webpack"],
    projects: 11,
    email: "sanjay.gupta@example.com",
  },
  {
    id: "member-8",
    name: "Lavanya Sharma",
    role: "QA Engineer",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 4.3,
    skills: ["Selenium", "Jest", "Cypress", "Postman", "JIRA"],
    projects: 6,
    email: "lavanya.sharma@example.com",
  },
]

export const sprintsData: Sprint[] = [
  {
    id: "sprint-1",
    projectId: "project-1",
    name: "Sprint 1 - Project Setup",
    startDate: new Date(2024, 2, 1),
    endDate: new Date(2024, 2, 14),
    tasks: [
      {
        id: "task-1",
        title: "Setup project repository",
        description: "Create GitHub repository and setup initial project structure",
        weightage: 3,
        status: "completed",
        assignee: "john.doe@example.com",
      },
      {
        id: "task-2",
        title: "Design database schema",
        description: "Create ERD and define database tables and relationships",
        weightage: 5,
        status: "in-progress",
        assignee: "jane.smith@example.com",
      },
      {
        id: "task-3",
        title: "Setup CI/CD pipeline",
        description: "Configure GitHub Actions for continuous integration and deployment",
        weightage: 8,
        status: "todo",
      },
    ],
  },
  {
    id: "sprint-2",
    projectId: "project-1",
    name: "Sprint 2 - Backend Development",
    startDate: new Date(2024, 2, 15),
    endDate: new Date(2024, 2, 28),
    tasks: [
      {
        id: "task-4",
        title: "Implement user authentication",
        description: "Create API endpoints for user registration, login, and password reset",
        weightage: 8,
        status: "completed",
        assignee: "john.doe@example.com",
      },
      {
        id: "task-5",
        title: "Create product management API",
        description: "Implement CRUD operations for products with categories, tags, and inventory management",
        weightage: 13,
        status: "in-progress",
        assignee: "alex.johnson@example.com",
      },
      {
        id: "task-6",
        title: "Implement order processing",
        description: "Create API endpoints for cart management and order processing",
        weightage: 8,
        status: "todo",
      },
    ],
  },
]

